---
- name: Include specific Icinga 2
  include: install-icinga2-package-debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific Icinga 2
  include: install-icinga2-package-redhat.yml
  when: ansible_os_family == 'RedHat'
