---
- name: Debian - Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Debian - Add Icinga 2 repository key
  apt_key:
    url: "{{ i2_apt_key }}"
    state: present

- name: Debian - Add Icinga 2 repository
  apt_repository:
    repo: "{{ i2_apt_url }}"
    state: present

- name: Debian - Ensure Icinga2 is installed
  apt:
    name: icinga2
    state: present
